version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.test
    container_name: server
    env_file:
      - .env
    environment:
      - NODE_ENV=test
    volumes:
      - ./server:/usr/src/app
    ports:
      - ${SRV_PORT}:${SRV_PORT}
    expose:
      - ${SRV_PORT}
    depends_on:
      - postgres
      - redis
    networks:
      - server_postgres
      - server_redis
    command: ["./wait-for-it.sh", "postgres:5432", "--", "./wait-for-it.sh", "redis:6379", "--", "yarn", "test"]
  postgres:
    image: postgres:12.4-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_ROOT_PASSWORD}
      - POSTGRES_CUSTOM_USER_PASSWORD=${POSTGRES_CUSTOM_USER_PASSWORD}
    volumes:
      - ${PWD}/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ${PWD}/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ${PWD}/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf' -c 'hba_file=/etc/postgresql/pg_hba.conf'
    user: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - server_postgres
  redis:
    image: redis:6.0.6-alpine
    container_name: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ${PWD}/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ${PWD}/redis/init.sh:/usr/local/etc/redis/init.sh
    command: sh -c "chmod +x /usr/local/etc/redis/init.sh && /usr/local/etc/redis/init.sh && redis-server /usr/local/etc/redis/redis.conf"
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - server_redis

networks:
  server_postgres:
    driver: bridge
  server_redis:
    driver: bridge
